version: "3.4"
   
services:
  db:
    image: postgres:12.12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    tty: true 
    build: .
    container_name: clinicapp_web
    command: ash -c "python /code/clinicapp/manage.py migrate && echo "yes" | python /code/clinicapp/manage.py flush && python /code/clinicapp/manage.py loaddata /code/clinicapp/data.json && python /code/clinicapp/manage.py runserver 0.0.0.0:8000"
    #command: ash -c "python /code/clinicapp/manage.py migrate && python /code/clinicapp/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

