version: "3.4"
   
services:
  db:
    image: postgres:12.12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    tty: true 
    build: .
    container_name: clinicapp_web
    command: ash -c "cd ../.. && python clinicapp/manage.py migrate && echo "yes" | python clinicapp/manage.py flush && python clinicapp/manage.py loaddata clinicapp/data.json && python clinicapp/manage.py runserver 0.0.0.0:8000"
    #command: ash -c "cd ../.. && python clinicapp/manage.py migrate && echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', password='0000') if not User.objects.filter(username='admin').exists() else None\" | python clinicapp/manage.py shell && python clinicapp/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - imagenes:/code/clinicapp/media

volumes:
  postgres_data:
  imagenes:
