# Generated by Django 4.1.5 on 2023-01-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('tipo', models.CharField(choices=[('cirugia', 'cirugia'), ('pequeña cirugia', 'pequeña cirugia'), ('trat facial', 'trat facial'), ('trat corporal', 'trat corporal')], default='informacion', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(choices=[('informacion', 'informacion'), ('medicina familiar', 'medicina familiar'), ('consulta', 'consulta'), ('revision', 'revision')], default='informacion', max_length=20)),
                ('observaciones_auxiliar', models.TextField()),
                ('observaciones_doctor', models.TextField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_antes', models.ImageField(upload_to='imagenes', verbose_name='fotoAntes')),
                ('foto_despues', models.ImageField(upload_to='imagenes', verbose_name='fotoDespues')),
                ('foto_consentimiento', models.ImageField(upload_to='imagenes', verbose_name='fotoConsentimiento')),
                ('foto_etiqueta', models.ImageField(upload_to='imagenes', verbose_name='fotoEtiqueta')),
                ('id_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visita.intervencion')),
                ('id_visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visita.visita')),
            ],
        ),
    ]
