# Generated by Django 4.1.5 on 2023-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencion',
            name='tipo',
            field=models.CharField(choices=[('CIRUGIA', 'CIRUGIA'), ('PEQUEÑA CIRUGIA', 'PEQUEÑA CIRUGIA'), ('TRAT FACIAL', 'TRAT FACIAL'), ('TRAT CORPORAL', 'TRAT CORPORAL')], default='PEQUEÑA CIRUGIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.CharField(choices=[('INFORMACION', 'INFORMACION'), ('MEDICINA FAMILIAR', 'MEDICINA FAMILIAR'), ('CONSULTA', 'CONSULTA'), ('REVISION', 'REVISION')], default='INFORMACION', max_length=20),
        ),
    ]
