# Generated by Django 4.1.5 on 2023-01-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0002_alter_intervencion_tipo_alter_visita_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='id_intervencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visita.intervencion'),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='id_visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visita.visita', unique=True),
        ),
    ]
