# Generated by Django 4.1.5 on 2023-01-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0004_alter_resultados_id_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencion',
            name='nombre',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='foto_antes',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='fotoAntes'),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='foto_despues',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='fotoDespues'),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='foto_etiqueta',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='fotoEtiqueta'),
        ),
    ]
