# Generated by Django 4.1.5 on 2023-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0005_alter_intervencion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='foto_consentimiento',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='fotoConsentimiento'),
        ),
    ]
