# Generated by Django 4.1.5 on 2023-02-10 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0018_alter_paciente_apellidos_alter_paciente_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visita', '0006_alter_resultados_foto_consentimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVisita',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(choices=[('INFORMACION', 'INFORMACION'), ('MEDICINA FAMILIAR', 'MEDICINA FAMILIAR'), ('CONSULTA', 'CONSULTA'), ('REVISION', 'REVISION')], default='INFORMACION', max_length=20)),
                ('observaciones_auxiliar', models.TextField()),
                ('observaciones_doctor', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'historical visita',
                'verbose_name_plural': 'historical visitas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalResultados',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('foto_antes', models.TextField(max_length=100, null=True, verbose_name='fotoAntes')),
                ('foto_despues', models.TextField(max_length=100, null=True, verbose_name='fotoDespues')),
                ('foto_consentimiento', models.TextField(max_length=100, null=True, verbose_name='fotoConsentimiento')),
                ('foto_etiqueta', models.TextField(max_length=100, null=True, verbose_name='fotoEtiqueta')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_intervencion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='visita.intervencion')),
                ('id_visita', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='visita.visita')),
            ],
            options={
                'verbose_name': 'historical resultados',
                'verbose_name_plural': 'historical resultadoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
