# Generated by Django 4.1.5 on 2023-02-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0007_historicalvisita_historicalresultados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalResultados',
        ),
    ]
