# Generated by Django 4.1.5 on 2023-01-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.TextField()),
                ('apellidos', models.TextField()),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexo', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], default='masculino', max_length=20)),
                ('pais', models.TextField()),
                ('comunidad', models.TextField()),
                ('alergias', models.ManyToManyField(to='paciente.alergia')),
                ('contextos', models.ManyToManyField(to='paciente.contexto')),
            ],
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.TextField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('id_farmaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.farmaco')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='prescripciones',
            field=models.ManyToManyField(through='paciente.Prescripcion', to='paciente.farmaco'),
        ),
    ]
