# Generated by Django 4.1.5 on 2023-01-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergia',
            name='nombre',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='contexto',
            name='nombre',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='farmaco',
            name='nombre',
            field=models.TextField(unique=True),
        ),
    ]
