# Generated by Django 4.1.5 on 2023-01-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_alter_paciente_quiere_informacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='quiere_informacion',
        ),
    ]
