# Generated by Django 4.1.5 on 2023-01-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_alter_paciente_quiere_informacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='comunidad',
            field=models.CharField(choices=[('ANDALUCÍA', 'ANDALUCÍA'), ('ARAGÓN', 'ARAGÓN'), ('PRINCIPADO DE ASTURIAS', 'PRINCIPADO DE ASTURIAS'), ('ISLAS BALEARES', 'ISLAS BALEARES'), ('CANARIAS', 'CANARIAS'), ('CANTABRIA', 'CANTABRIA'), ('CASTILLA-LA MANCHA', 'CASTILLA-LA MANCHA'), ('CASTILLA Y LEÓN', 'CASTILLA Y LEÓN'), ('CATALUÑA', 'CATALUÑA'), ('COMUNIDAD VALENCIANA', 'COMUNIDAD VALENCIANA'), ('EXTREMADURA', 'EXTREMADURA'), ('GALICIA', 'GALICIA'), ('COMUNIDAD DE MADRID', 'COMUNIDAD DE MADRID'), ('REGIÓN DE MURCIA', 'REGIÓN DE MURCIA'), ('NAVARRA', 'NAVARRA'), ('PAÍS VASCO', 'PAÍS VASCO'), ('LA RIOJA', 'LA RIOJA'), ('CEUTA', 'CEUTA'), ('MELILLA', 'MELILLA')], max_length=30),
        ),
    ]
