# Generated by Django 4.1.5 on 2023-01-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_alter_paciente_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='codigo_postal',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
