# Generated by Django 4.1.5 on 2023-01-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_paciente_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='codigo_postal',
            field=models.IntegerField(default=0),
        ),
    ]
