# Generated by Django 4.1.5 on 2023-02-10 10:19

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_alter_paciente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=254, unique=True)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=12)),
        ),
    ]
