# Generated by Django 4.1.5 on 2023-02-10 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0018_alter_paciente_apellidos_alter_paciente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaciente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dni', django_cryptography.fields.encrypt(models.CharField(db_index=True, max_length=9))),
                ('nombre', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('apellidos', django_cryptography.fields.encrypt(models.TextField())),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', django_cryptography.fields.encrypt(models.CharField(max_length=12))),
                ('email', django_cryptography.fields.encrypt(models.EmailField(db_index=True, max_length=254))),
                ('codigo_postal', models.IntegerField(default=0)),
                ('localidad', models.TextField(default='')),
                ('sexo', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], default='masculino', max_length=20)),
                ('comunidad', models.CharField(choices=[('ANDALUCÍA', 'ANDALUCÍA'), ('ARAGÓN', 'ARAGÓN'), ('PRINCIPADO DE ASTURIAS', 'PRINCIPADO DE ASTURIAS'), ('ISLAS BALEARES', 'ISLAS BALEARES'), ('CANARIAS', 'CANARIAS'), ('CANTABRIA', 'CANTABRIA'), ('CASTILLA-LA MANCHA', 'CASTILLA-LA MANCHA'), ('CASTILLA Y LEÓN', 'CASTILLA Y LEÓN'), ('CATALUÑA', 'CATALUÑA'), ('COMUNIDAD VALENCIANA', 'COMUNIDAD VALENCIANA'), ('EXTREMADURA', 'EXTREMADURA'), ('GALICIA', 'GALICIA'), ('COMUNIDAD DE MADRID', 'COMUNIDAD DE MADRID'), ('REGIÓN DE MURCIA', 'REGIÓN DE MURCIA'), ('NAVARRA', 'NAVARRA'), ('PAÍS VASCO', 'PAÍS VASCO'), ('LA RIOJA', 'LA RIOJA'), ('CEUTA', 'CEUTA'), ('MELILLA', 'MELILLA')], max_length=30)),
                ('pais', models.TextField()),
                ('quiere_informacion', models.BooleanField(default=False)),
                ('vino_de', models.TextField(default='Web')),
                ('foto_consentimiento', models.TextField(default='/media/imagenes/casa_herborista.jpg', max_length=100, verbose_name='fotoConsentimiento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical paciente',
                'verbose_name_plural': 'historical pacientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
