# Generated by Django 4.1.5 on 2023-02-20 18:54

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0019_historicalpaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='direccion',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
