# Generated by Django 4.1.5 on 2023-01-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_programada', models.DateTimeField()),
                ('motivo', models.CharField(choices=[('informacion', 'informacion'), ('medicina familiar', 'medicina familiar'), ('consulta', 'consulta'), ('revision', 'revision')], default='informacion', max_length=20)),
                ('nombre', models.TextField()),
                ('apellidos', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
                ('es_paciente', models.BooleanField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
