# Generated by Django 4.1.5 on 2023-01-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_alter_paciente_codigo_postal'),
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(choices=[('INFORMACION', 'INFORMACION'), ('MEDICINA FAMILIAR', 'MEDICINA FAMILIAR'), ('CONSULTA', 'CONSULTA'), ('REVISION', 'REVISION')], default='INFORMACION', max_length=20),
        ),
    ]
