# Generated by Django 4.1.5 on 2023-01-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_alter_paciente_codigo_postal'),
        ('cita', '0002_alter_cita_id_paciente_alter_cita_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
