# Generated by Django 4.1.5 on 2023-01-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_alter_cita_id_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='es_paciente',
        ),
    ]
