# Generated by Django 4.1.5 on 2023-01-26 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0005_cita_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='duracion',
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_terminacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 11, 45, 47, 616155, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
